SELECT CONCAT(Name,'(',SUBSTRING(Occupation, 1, 1),')') AS Name
FROM OCCUPATIONS
ORDER BY Name ASC;

SELECT CONCAT('There are a total of ',COUNT(*),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS 
GROUP BY Occupation
ORDER BY COUNT(*) ASC ,OCCUPATION ASC;